name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements/ci.txt

      - name: Configure DVC S3 authentication
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          dvc remote modify dagshub-s3 access_key_id "$DAGSHUB_TOKEN" --local
          dvc remote modify dagshub-s3 secret_access_key "$DAGSHUB_TOKEN" --local

      - name: Check DVC object
        run: |
          curl -I \
            -u "kush2501:$DAGSHUB_TOKEN" \
            "https://dagshub.com/kush2501/credit-risk-prediction-mlops.dvc/files/md5/6c/a2272a24b34d679ffb76176562f182"

      - name: Check DagsHub identity
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          curl -u "kush2501:$DAGSHUB_TOKEN" https://dagshub.com/api/v1/user

      - name: Check DVC remote
        run: dvc status -c -v

      - name: Pull DVC artifacts
        run: dvc pull


      - name: Run tests
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: pytest -v
